base:
  app_chain_type: fisco # application chain type
  store_path: .db # store path

# iservice config
iservice:
  chain_id: irita-hub
  node_rpc_addr: http://127.0.0.1:26657
  node_grpc_addr: 127.0.0.1:9090
  key_path: .keys/iservice
  key_name: provider
  passphrase: 12345678

# fisco config
fisco:
  connection_type: channel
  ca_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/ca.crt
  cert_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/sdk.crt
  key_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/sdk.key
  sm_crypto: false
  priv_key_file: /Users/bianjie/BSN/bsnhub-service-relayer/keys/key.pem
  node_url: 60.247.61.162:20200
